### ISSUE TITLE
is_divisible doesn't work along the 64-bit boundary of integers

### ISSUE THREAD

**Issue by fsh** [BrianGladman/gmpy2#7]
`mpz.is_divisible` and `gmpy2.is_divisible` fails to work correctly when the divisor is in range `[2^63, 2^64)`, probably due to some integer conversion issues(?).

```python
>>> q=mpz(randrange(2**63,2**64))
>>> (2*q).is_divisible(q)
False
>>> gmpy2.is_divisible(2*q, q)
False
```

But if the number is smaller or bigger it works:

```python
>>> p=mpz(randrange(2**62,2**63))
>>> (2*p).is_divisible(p)
True
>>> p=mpz(randrange(2**64,2**65))
>>> (2*p).is_divisible(p)
True
```

**Comment by BrianGladman** [comment]
HI, Your example works fine for me:

>>> from gmpy2 import mpz
>>> from random import randrange
>>> q=mpz(randrange(2 ** 63, 2 ** 64))
>>> (2*q).is_divisible(q)
True

Have you updated GMPY2 recently?   

This is necessary since there have been recent bug fixes and this may be one of them.

Of course, we don't know what actual q value you are using and it would be necessary to know this so that I can  test this exact value.

**Comment by fsh** [comment]
Hmm, I'm using v 2.1.2 from pip which seems to be the latest(?).

It seems it does succeed sometimes, but mostly fails; here's with printing the numbers:

```python
>>> print(q := gmpy2.mpz(2 * random.getrandbits(63) + 1))
13157547707030902665
>>> (2*q).is_divisible(q)
False
>>> print(q := gmpy2.mpz(2 * random.getrandbits(63) + 1))
1070317427780135395
>>> (2*q).is_divisible(q)
True
>>> print(q := gmpy2.mpz(2 * random.getrandbits(63) + 1))
18019609787501108695
>>> (2*q).is_divisible(q)
False
>>> print(q := gmpy2.mpz(2 * random.getrandbits(63) + 1))
3978762157568107671
>>> (2*q).is_divisible(q)
True
>>> print(q := gmpy2.mpz(2 * random.getrandbits(63) + 1))
14444587867185512177
>>> (2*q).is_divisible(q)
False
>>> (2*q)
mpz(28889175734371024354)
>>> (2*q) // 2
mpz(14444587867185512177)
>>> (2*q) // 2 == q
True
>>> (2*q).is_divisible(q)
False
>>> gmpy2.version(), gmpy2.mp_version()
('2.1.2', 'GMP 6.2.1')
```

This is archlinux, Python 3.10.5.

**Comment by BrianGladman** [comment]
I have checked your values on my Windows version of GMPY2 and there re no errors:
> from gmpy2 import mpz
> q=mpz('13157547707030902665')
> (2*q).is_divisible(q)
> True
> q=mpz('1070317427780135395')
> (2*q).is_divisible(q)
> True
> q=mpz('18019609787501108695')
> (2*q).is_divisible(q)
> True
> q=mpz('3978762157568107671')
> (2*q).is_divisible(q)
> True
> q=mpz('14444587867185512177')
> (2*q).is_divisible(q)
> True

This repository is a clone of the GMPY2 master repository and only maintains the Windows build using MPIR rather than the GMP multiple precision library.   This means that the code used within GMPY2 on Windows provided here is significantly different from that used on Linux

In consequence, since you are using the Linux version, I cannot offer you any help here and you will need to report your issues on the master repository site [https://github.com/aleaxit/gmpy/](https://github.com/aleaxit/gmpy/).

**Comment by fsh** [comment]
Ah, my apologies, I wasn't aware it wasn't the master, it was the first link that was given by Google and I missed that part in the readme. I'll report it over there.
